local mp_globals = {
    mp = {
        fields = {
            command = {},
            commandv = {},
            command_native = {},
            command_native_async = {},
            add_hook = {},
            abort_async_command = {},
            del_property = {},
            get_property = {},
            get_property_osd = {},
            get_property_bool = {},
            get_property_number = {},
            get_property_native = {},
            set_property = {},
            set_property_bool = {},
            set_property_number = {},
            set_property_native = {},
            get_time = {},
            add_key_binding = {},
            add_forced_key_binding = {},
            remove_key_binding = {},
            register_event = {},
            unregister_event = {},
            observe_property = {},
            unobserve_property = {},
            add_timeout = {},
            add_periodic_timer = {},
            get_opt = {},
            get_script_name = {},
            get_script_directory = {},
            osd_message = {},
            get_wakeup_pipe = {},
            get_next_timeout = {},
            dispatch_events = {},
            register_idle = {},
            unregister_idle = {},
            enable_messages = {},
            register_script_message = {},
            unregister_script_message = {},
            create_osd_overlay = {},
            get_osd_size = {},
            msg = {
                fields = {
                    fatal = {},
                    error = {},
                    warn = {},
                    info = {},
                    verbose = {},
                    debug = {},
                    trace = {},
                }
            },
            -- Not documented
            -- TODO: Document or remove them
            disable_key_bindings = {},
            enable_key_bindings = {},
            find_config_file = {},
            flush_keybindings = {},
            format_time = {},
            get_mouse_pos = {},
            set_key_bindings = {},
            set_mouse_area = {},
            set_osd_ass = {},
        }
    },
    exit = {},
    unpack = {},
}
